[package]
name = "vvk"
version = "0.1.0"

[lib]
name = "vvk"
module = "vvk"
archive = "vvk"

[usage]
public-include-directories = ["include"]

[dependencies.rstd-std]
version = "0.1.0"
pub = true

[dependencies.rstd-cppstd]
version = "0.1.0"
pub = true

[dependencies.rstd-dlopn]
version = "0.1.0"
pub = true

[dependencies.rstd-log]
version = "0.1.0"

[external-dependencies.cmake.vulkan]
package = "VulkanHeaders"
targets = [{ name = "Vulkan::Headers", pub = true }]

[external-sources.vma]
git = "https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator.git"
rev = "3aa921224c154a0d2c43912bc88e1c42ce1f7607"

[external-dependencies.cmake.vma]
package = "VulkanMemoryAllocator"
source = "vma"
cache = {
  VMA_BUILD_DOCUMENTATION = false,
  VMA_BUILD_SAMPLES = false,
  VMA_ENABLE_INSTALL = true,
}
targets = [{ name = "GPUOpen::VulkanMemoryAllocator", pub = true }]

[[test]]
name = "vvk-memory-tests"
sources = ["tests/main.cpp", "tests/memory.cpp", "tests/memory_vulkan.cpp", "tests/memory_import.cpp", "tests/dispatch.cpp"]

[dev-dependencies]
rstd-test = { version = "0.1.0" }
