[package]
name = "vvk"
version = "0.1.0"

[lib]
name = "vvk"
module = "vvk"
archive = "vvk"
discovery = "module"

[usage]
public-include-directories = ["include"]

[dependencies.rstd-std]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.rstd-cppstd]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.rstd-log]
git = "https://github.com/litocpp/rstd.git"
visibility = "private"

[external-dependencies.cmake.vulkan]
find-package = "Vulkan"
targets = [{ name = "Vulkan::Vulkan", visibility = "public" }]

[external-dependencies.cmake.vma]
find-package = "VulkanMemoryAllocator"
git = "https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator.git"
rev = "3aa921224c154a0d2c43912bc88e1c42ce1f7607"
cache = {
  VMA_BUILD_DOCUMENTATION = false,
  VMA_BUILD_SAMPLES = false,
  VMA_ENABLE_INSTALL = true,
}
targets = [{ name = "GPUOpen::VulkanMemoryAllocator", visibility = "public" }]
