[package]
name = "vvk"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["hypengw <hypengwip@gmail.com>"]

[lib]
name = "vvk"
module = "vvk"
archive = "vvk"

[usage]
public-include-directories = ["include"]

[dependencies.rstd-std]
version = "0.1.0"
pub = true

[dependencies.rstd-cppstd]
version = "0.1.0"
pub = true

[dependencies.rstd-dlopn]
version = "0.1.0"
pub = true

[dependencies.rstd-log]
version = "0.1.0"

[external-dependencies.cmake.vulkan]
package = "VulkanHeaders"
targets = [{ name = "Vulkan::Headers", pub = true }]

[[test]]
name = "vvk-memory-tests"
sources = ["tests/main.cpp", "tests/memory.cpp", "tests/memory_vulkan.cpp", "tests/memory_import.cpp", "tests/dispatch.cpp", "tests/format.cpp"]

[dev-dependencies]
rstd-test = { version = "0.1.0" }
