#!/usr/bin/env python3
"""Regenerate the checked-in Vulkan headers and module partitions."""

import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET


ROOT = Path(__file__).resolve().parents[2]
PIN = json.loads((Path(__file__).with_name("registry.json")).read_text())
NOTICE = "// Generated by tools/vulkan/generate.py; do not edit.\n// clang-format off\n"
CONTROL_MACROS = {
    "VK_DEFINE_HANDLE", "VK_DEFINE_NON_DISPATCHABLE_HANDLE",
    "VK_USE_64_BIT_PTR_DEFINES", "VK_API_VERSION",
}


def run(*args, **kwargs):
    return subprocess.run(args, check=True, text=True, **kwargs)


def verify_upstream(path):
    commit = run("git", "-C", str(path), "rev-parse", "HEAD", capture_output=True).stdout.strip()
    if commit != PIN["commit"]:
        raise ValueError(f"expected upstream commit {PIN['commit']}, got {commit}")
    status = run("git", "-C", str(path), "status", "--porcelain", "--untracked-files=all",
                 capture_output=True).stdout
    if status:
        raise ValueError("upstream checkout must be clean")
    for name, digest in PIN["sha256"].items():
        if hashlib.sha256((path / name).read_bytes()).hexdigest() != digest:
            raise ValueError(f"upstream input checksum mismatch: {name}")


def vulkan(element, key="api"):
    return "vulkan" in element.get(key, "vulkan").split(",")


def defined(name):
    return f"defined({name})"


def dependency(value):
    if not value:
        return "1"
    tokens = re.findall(r"VK_\w+|[+,()]", value)
    if "".join(tokens) != value:
        raise ValueError(f"unsupported dependency expression: {value}")
    return "(" + " ".join({"+": "&&", ",": "||"}.get(t, defined(t) if t.startswith("VK_") else t)
                           for t in tokens) + ")"


def both(*conditions):
    parts = sorted(set(c for c in conditions if c != "1"))
    return " && ".join(parts) or "1"


class Registry:
    """One parsed registry owns symbol classification and availability."""

    def __init__(self, source):
        self.root = ET.parse(source).getroot()
        self.types = {t.get("name") or t.findtext("name") or t.findtext("proto/name"): t
                      for t in self.root.findall("types/type") if vulkan(t)}
        self.groups = {g.get("name"): g for g in self.root.findall("enums")}
        self.commands = {c.get("name") or c.findtext("proto/name"): c
                         for c in self.root.findall("commands/command") if vulkan(c)}
        self.symbols = {"types": {}, "functions": {}, "constants": {}}
        self.defines = {}
        platforms = {p.get("name"): p.get("protect") for p in self.root.findall("platforms/platform")}
        features = list(self.root.findall("feature"))
        extensions = list(self.root.findall("extensions/extension"))
        for feature in features + extensions:
            if not vulkan(feature, "supported" if feature.tag == "extension" else "api"):
                continue
            name = re.sub(r"VK_(BASE|COMPUTE|GRAPHICS)_VERSION_", "VK_VERSION_", feature.get("name"))
            guards = [defined(name)]
            if feature.get("platform"):
                guards.append(defined(platforms[feature.get("platform")]))
            if feature.get("provisional") == "true":
                guards.append(defined("VK_ENABLE_BETA_EXTENSIONS"))
            for require in feature.findall("require"):
                if not vulkan(require) or not any(item.tag in {"type", "command", "enum"} for item in require):
                    continue
                guard = both(*guards, dependency(require.get("depends")))
                for item in require:
                    if not vulkan(item):
                        continue
                    item_guard = both(guard, defined(item.get("protect")) if item.get("protect") else "1")
                    symbol = item.get("name")
                    if item.tag == "type":
                        self.add_type(symbol, item_guard, set())
                    elif item.tag == "command":
                        self.add("functions", "PFN_" + symbol, item_guard)
                        command = self.commands[symbol]
                        while command.get("alias"):
                            command = self.commands[command.get("alias")]
                        for related in command.findall(".//type"):
                            self.add_type(related.text, item_guard, set())
                    elif item.tag == "enum":
                        if item.get("extends"):
                            self.add("types", symbol, item_guard)
                        else:
                            # Standalone macros share the emitted header's feature guard.
                            self.add("constants", symbol, defined(name))
        for feature in features:
            name = feature.get("name")
            if vulkan(feature) and re.fullmatch(r"VK_VERSION_\d+_\d+", name):
                self.add("constants", name, defined(name))

    def add(self, section, name, guard):
        self.symbols[section].setdefault(name, set()).add(guard)

    def add_type(self, name, guard, visiting):
        if name in visiting or name not in self.types:
            return
        visiting = visiting | {name}
        element = self.types[name]
        category = element.get("category")
        if category == "define":
            if name in CONTROL_MACROS:
                return
            self.defines[name] = "".join(element.itertext())
            self.add("constants", name, guard)
        elif category in {"basetype", "bitmask", "handle", "enum", "struct", "union", "funcpointer"}:
            self.add("functions" if category == "funcpointer" else "types", name, guard)
            group = self.groups.get(name)
            if category == "enum" and group is not None and not element.get("alias"):
                for enum in group.findall("enum"):
                    if vulkan(enum):
                        extra = defined(enum.get("protect")) if enum.get("protect") else "1"
                        self.add("types", enum.get("name"), both(guard, extra))
                if group.get("type") == "enum":
                    # Match Khronos's enum sentinel naming, including vendor suffixes.
                    vendor = re.search(r"(KHR|EXT|[A-Z][A-Z0-9]+)$", name)
                    prefix = "VK_" if name.startswith("Vk") else ""
                    start = 2 if prefix else 0
                    base = name[start:vendor.start()] if vendor else name[start:]
                    words = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", base).upper()
                    sentinel = prefix + words + "_MAX_ENUM" + ("_" + vendor.group() if vendor else "")
                    self.add("types", sentinel, guard)
        for related in (element.get("alias"), element.get("requires"), element.get("bitvalues")):
            if related:
                self.add_type(related, guard, visiting)
        for related in element.findall(".//type"):
            if related.text:
                self.add_type(related.text, guard, visiting)

    def entries(self, section):
        for name, guards in sorted(self.symbols[section].items()):
            guard = "1" if "1" in guards else " || ".join(f"({g})" for g in sorted(guards))
            yield name, guard

    def export_groups(self, section):
        groups = {}
        for name, guard in self.entries(section):
            groups.setdefault(guard, []).append(name)
        return sorted(groups.items())


def guarded(guard, text):
    return text if guard == "1" else f"#if {guard}\n{text}#endif\n"


def partition(section, registry):
    prefix = NOTICE + "module;\n\n#define VK_NO_PROTOTYPES\n#include <vulkan/vulkan.h>\n\n"
    exports = []
    if section != "constants":
        for guard, names in registry.export_groups(section):
            exports.append(guarded(guard, "".join(f"    using ::{name};\n" for name in names)))
    else:
        captures, undefs = [], []
        for index, (guard, names) in enumerate(registry.export_groups(section)):
            group_captures, group_exports = [], []
            for name in names:
                if name == "VK_NULL_HANDLE":
                    continue
                definition = registry.defines.get(name, "")
                function = re.search(r"#define\s+" + name + r"\(([^)]*)\)", definition)
                if function:
                    args = [arg.strip() for arg in function.group(1).split(",")]
                    if not all(re.fullmatch(r"[a-z]+", arg) for arg in args):
                        raise ValueError(f"unclassified macro: {name}")
                    params = ", ".join(f"uint32_t {arg}" for arg in args)
                    values = ", ".join(args)
                    capture = f"inline constexpr uint32_t vvk_capture_{name}({params}) {{ return {name}({values}); }}\n"
                    exported = f"    inline constexpr uint32_t {name}({params}) {{ return vvk_capture_{name}({values}); }}\n"
                else:
                    capture = f"inline constexpr auto vvk_capture_{name} = {name};\n"
                    exported = f"    inline constexpr auto {name} = vvk_capture_{name};\n"
                group_captures.append(capture)
                group_exports.append(exported)
                undefs.append(f"#undef {name}\n")
            if not group_exports:
                continue
            # Freeze availability before undefining the exported version macros.
            marker = f"VVK_EXPORT_CONSTANTS_{index}"
            captures.append(guarded(guard, f"#define {marker}\n" + "".join(group_captures)))
            exports.append(f"#ifdef {marker}\n" + "".join(group_exports) + f"#undef {marker}\n#endif\n")
        prefix += "".join(captures) + "\n" + "".join(undefs)
        prefix += "\n#undef VK_NULL_HANDLE\n"
        exports.append("    struct VulkanNullHandle {\n"
                       "        constexpr operator uint64_t() const noexcept { return 0; }\n"
                       "        template<class T> constexpr operator T*() const noexcept { return nullptr; }\n"
                       "    };\n    inline constexpr VulkanNullHandle VK_NULL_HANDLE {};\n")
    return prefix + f"\nexport module vvk:ffi.vulkan.{section};\n\nexport {{\n" + "".join(exports) + "}\n"


def generate(upstream, output):
    header_dir = output / "include/vulkan"
    video_dir = output / "include/vk_video"
    header_dir.mkdir(parents=True)
    video_dir.mkdir(parents=True)
    for directory in (header_dir, video_dir):
        (directory / ".clang-format").write_text("DisableFormat: true\n")
    # The upstream public Makefile owns the complete Vulkan and video header target list.
    run("make", "-C", str(upstream / "xml"), "-j2", "install", "codec_headers",
        f"PYTHON={sys.executable}", f"GENERATED={output / 'upstream'}", f"INCLUDE={output / 'include'}")
    registry = Registry(upstream / "xml/vk.xml")
    video = Registry(upstream / "xml/video.xml")
    registry.defines.update(video.defines)
    for section, symbols in video.symbols.items():
        for name, guards in symbols.items():
            registry.symbols[section].setdefault(name, set()).update(guards)
    for header in header_dir.glob("*.h"):
        text = header.read_text()
        # Preserve the C declaration; give C++ constants external inline linkage for module export.
        text = re.sub(r"^static const (Vk\w+ VK_\w+ = [^;]+;)$",
                      r"#if defined(__cplusplus) && __cplusplus >= 201703L\ninline constexpr \1\n#else\nstatic const \1\n#endif",
                      text, flags=re.M)
        header.write_text(text)
    for section in registry.symbols:
        path = output / f"src/ffi/vulkan/{section}.cppm"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(partition(section, registry))
    licenses = output / "include/vulkan/licenses"
    licenses.mkdir()
    for name in ("Apache-2.0.txt", "MIT.txt"):
        shutil.copyfile(upstream / "LICENSES" / name, licenses / name)
    return {str(p.relative_to(output)): p.read_bytes()
            for base in (output / "include", output / "src") for p in base.rglob("*") if p.is_file()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--upstream", type=Path, help="clean pinned Vulkan-Docs checkout; otherwise fetch into /tmp")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="vvk-vulkan-", dir="/tmp") as temporary:
        temporary = Path(temporary)
        if args.upstream:
            upstream = args.upstream.resolve()
        else:
            upstream = temporary / "upstream-source"
            run("git", "init", "--quiet", str(upstream))
            run("git", "-C", str(upstream), "fetch", "--quiet", "--depth=1", PIN["repository"], PIN["commit"])
            run("git", "-C", str(upstream), "checkout", "--quiet", "--detach", "FETCH_HEAD")
        verify_upstream(upstream)
        outputs = generate(upstream, temporary / "generated")
        changed = [name for name, data in outputs.items()
                   if not (ROOT / name).exists() or (ROOT / name).read_bytes() != data]
        managed = [ROOT / "include/vulkan", ROOT / "include/vk_video"]
        stale = [p for directory in managed for p in directory.rglob("*")
                 if p.is_file() and str(p.relative_to(ROOT)) not in outputs]
        for name in changed:
            path = ROOT / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(outputs[name])
        for path in stale:
            path.unlink()
        print(f"Vulkan {PIN['version']}: {len(outputs)} outputs, {len(changed)} changed, {len(stale)} stale")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, subprocess.CalledProcessError) as error:
        sys.exit(str(error))
